const mesajEroare = {
  item: "0",
  image: "Gallery/error404.jpg",
  title: "ERROR",
  shortDescription: `Product not found`,
  link: "gallery.html",
  btnText1: "Back",
  btnText2: "Back",
  dataAosDelay: "0",
  fullDescription: ``,
};

const pipe1 = {
  item: "1",
  image: "Gallery/Rasova/La-Plage-Rose.png",
  image1: "",
  image2: "",
  image3: "",
  image4: "",
  image5: "",
  title: "La Plage D'Amour Rosé",
  shortDescription: `Rosé`,
  link: "",
  btnText1: "Details",
  btnText2: "",
  dataAosDelay: "0",
  specs: {
    color: "Rosé",
    year: "2024",
    grapeVariety: "Pinot Noir & Fetească Neagră & Syrah",
    wineType: "Dry",
    bottleVolume: "750 ml",
    alcoholContent: "12.5%",
    qualityClassification: "C.D.O. - Murfatlar vineyard",
    priceWithoutVAT: "EUR 12",
  },
  fullDescription: `It displays a delicate, luminous peach-pink hue that immediately catches the eye. On the nose, it unfolds with a fresh, lively, and generous aromatic profile, offering well-defined fruity notes of raspberry, white blossoms, wild strawberries, and crisp red apples. The intensity is above average, yet beautifully balanced, expressing a charming and approachable character.<br><br>

On the palate, it is light and fruit-driven, with vibrant hints of pink grapefruit and pomegranate adding an appealing twist. The finish is tonic, refreshing, and pleasantly crisp, leaving a clean and invigorating impression. An easy-drinking, friendly wine that captivates through its expressive and intense aromas.`,
};

const pipe2 = {
  item: "2",
  image: "Gallery/Rasova/Sur-Mer-Rose.png",
  image1: "",
  image2: "",
  image3: "",
  image4: "",
  image5: "",
  title: "Sur Mer Rosé",
  shortDescription: `Rosé`,
  link: "",
  btnText1: "Details",
  btnText2: "",
  dataAosDelay: "0",
  specs: {
    color: "Rosé",
    year: "2024",
    grapeVariety: "",
    wineType: "Dry",
    bottleVolume: "75 cl",
    alcoholContent: "13.3%",
    qualityClassification: "",
    priceWithoutVAT: "EUR 14",
  },
  fullDescription: ``,
};

const pipe3 = {
  item: "3",
  image: "Gallery/Rasova/La-Plage-White.png",
  image1: "",
  image2: "",
  image3: "",
  image4: "",
  image5: "",
  title: "La Plage",
  shortDescription: `White`,
  link: "",
  btnText1: "Details",
  btnText2: "",
  dataAosDelay: "0",
  specs: {
    color: "White",
    year: "2024",
    grapeVariety: "",
    wineType: "Dry",
    bottleVolume: "75 cl",
    alcoholContent: "12.5%",
    qualityClassification: "",
    priceWithoutVAT: "EUR 12",
  },
  fullDescription: ``,
};

const pipe4 = {
  item: "4",
  image: "Gallery/Recas/Sole-Feteasca-Regala.png",
  image1: "",
  image2: "",
  image3: "",
  image4: "",
  image5: "",
  title: "Sole Feteasca Regala",
  shortDescription: `White`,
  link: "",
  btnText1: "Details",
  btnText2: "",
  dataAosDelay: "0",
  specs: {
    color: "White",
    year: "2024",
    grapeVariety: "",
    wineType: "Dry",
    bottleVolume: "75 cl",
    alcoholContent: "13.5%",
    qualityClassification: "",
    priceWithoutVAT: "EUR 16.5",
  },
  fullDescription: ``,
};

const pipe5 = {
  item: "5",
  image: "Gallery/Recas/Sole-Rose.png",
  image1: "",
  image2: "",
  image3: "",
  image4: "",
  image5: "",
  title: "Sole Rosé",
  shortDescription: `Rosé`,
  link: "",
  btnText1: "Details",
  btnText2: "",
  dataAosDelay: "0",
  specs: {
    color: "Rosé",
    year: "2024",
    grapeVariety: "",
    wineType: "Dry",
    bottleVolume: "75 cl",
    alcoholContent: "11.5%",
    qualityClassification: "",
    priceWithoutVAT: "EUR 16.5",
  },
  fullDescription: ``,
};

const pipe6 = {
  item: "6",
  image: "Gallery/Recas/IMplicit-Rose.png",
  image1: "",
  image2: "",
  image3: "",
  image4: "",
  image5: "",
  title: "IMplicit Rosé",
  shortDescription: `Rosé`,
  link: "",
  btnText1: "Details",
  btnText2: "",
  dataAosDelay: "0",
  specs: {
    color: "Rosé",
    year: "2024",
    grapeVariety: "",
    wineType: "Dry",
    bottleVolume: "75 cl",
    alcoholContent: "13%",
    qualityClassification: "",
    priceWithoutVAT: "EUR 13",
  },
  fullDescription: ``,
};

const pipe7 = {
  item: "7",
  image: "Gallery/Oprisor/Rusalca-White.png",
  image1: "",
  image2: "",
  image3: "",
  image4: "",
  image5: "",
  title: "Rusalca White",
  shortDescription: `White`,
  link: "",
  btnText1: "Details",
  btnText2: "",
  dataAosDelay: "0",
  specs: {
    color: "White",
    year: "",
    grapeVariety: "",
    wineType: "Dry",
    bottleVolume: "75 cl",
    alcoholContent: "14%",
    qualityClassification: "",
    priceWithoutVAT: "EUR 16",
  },
  fullDescription: ``,
};

const pipe8 = {
  item: "8",
  image: "Gallery/Oprisor/La-Cetate-Tamaioasa-Romaneasca.png",
  image1: "",
  image2: "",
  image3: "",
  image4: "",
  image5: "",
  title: "La Cetate Tamaioasa Romaneasca",
  shortDescription: `White`,
  link: "",
  btnText1: "Details",
  btnText2: "",
  dataAosDelay: "0",
  specs: {
    color: "White",
    year: "",
    grapeVariety: "",
    wineType: "Semi-Dry",
    bottleVolume: "75 cl",
    alcoholContent: "14.5%",
    qualityClassification: "",
    priceWithoutVAT: "EUR 13",
  },
  fullDescription: ``,
};

const pipe9 = {
  item: "9",
  image: "Gallery/Oprisor/Jiana-Rose.png",
  image1: "",
  image2: "",
  image3: "",
  image4: "",
  image5: "",
  title: "Jiana Rosé",
  shortDescription: `Rosé`,
  link: "",
  btnText1: "Details",
  btnText2: "",
  dataAosDelay: "0",
  specs: {
    color: "Rosé",
    year: "",
    grapeVariety: "",
    wineType: "Dry",
    bottleVolume: "75 cl",
    alcoholContent: "13%",
    qualityClassification: "",
    priceWithoutVAT: "EUR 14",
  },
  fullDescription: ``,
};

const pipe10 = {
  item: "10",
  image: "Gallery/Oprisor/Caloian-Rose.png",
  image1: "",
  image2: "",
  image3: "",
  image4: "",
  image5: "",
  title: "Caloian Rosé",
  shortDescription: `Rosé`,
  link: "",
  btnText1: "Details",
  btnText2: "",
  dataAosDelay: "0",
  specs: {
    color: "Rosé",
    year: "",
    grapeVariety: "",
    wineType: "Dry",
    bottleVolume: "75 cl",
    alcoholContent: "13.5%",
    qualityClassification: "",
    priceWithoutVAT: "EUR 14",
  },
  fullDescription: ``,
};

const pipe11 = {
  item: "11",
  image: "Gallery/Oprisor/La-Cetate-Feteasca-Neagra.png",
  image1: "",
  image2: "",
  image3: "",
  image4: "",
  image5: "",
  title: "La Cetate Feteasca Neagra",
  shortDescription: `Red`,
  link: "",
  btnText1: "Details",
  btnText2: "",
  dataAosDelay: "0",
  specs: {
    color: "Red",
    year: "",
    grapeVariety: "",
    wineType: "Dry",
    bottleVolume: "75 cl",
    alcoholContent: "14.5%",
    qualityClassification: "",
    priceWithoutVAT: "EUR 13",
  },
  fullDescription: ``,
};

const pipe12 = {
  item: "12",
  image: "Gallery/Oprisor/Caloian-Feteasca-Neagra.png",
  image1: "",
  image2: "",
  image3: "",
  image4: "",
  image5: "",
  title: "Caloian Feteasca Neagra",
  shortDescription: `Red`,
  link: "",
  btnText1: "Details",
  btnText2: "",
  dataAosDelay: "0",
  specs: {
    color: "Red",
    year: "",
    grapeVariety: "",
    wineType: "Dry",
    bottleVolume: "75 cl",
    alcoholContent: "14%",
    qualityClassification: "",
    priceWithoutVAT: "EUR 12",
  },
  fullDescription: ``,
};

const pipe13 = {
  item: "13",
  image: "Gallery/Oprisor/Dragaica-Rosie.png",
  image1: "",
  image2: "",
  image3: "",
  image4: "",
  image5: "",
  title: "Dragaica Rosie",
  shortDescription: `Red`,
  link: "",
  btnText1: "Details",
  btnText2: "",
  dataAosDelay: "0",
  specs: {
    color: "Red",
    year: "",
    grapeVariety: "",
    wineType: "Dry",
    bottleVolume: "75 cl",
    alcoholContent: "14%",
    qualityClassification: "",
    priceWithoutVAT: "EUR 17",
  },
  fullDescription: ``,
};

const pipe14 = {
  item: "14",
  image: "Gallery/Oprisor/Feteasca-Neagra-Premium.png",
  image1: "",
  image2: "",
  image3: "",
  image4: "",
  image5: "",
  title: "Feteasca Neagra Premium",
  shortDescription: `Red`,
  link: "",
  btnText1: "Details",
  btnText2: "",
  dataAosDelay: "0",
  specs: {
    color: "Red",
    year: "",
    grapeVariety: "Feteasca neagra",
    wineType: "Dry",
    bottleVolume: "75 cl",
    alcoholContent: "14.9%",
    qualityClassification: "",
    priceWithoutVAT: "EUR 32",
  },
  fullDescription: ``,
};

const pipe15 = {
  item: "15",
  image: "Gallery/Pietroasa/Selectie-Feteasca-Alba.png",
  image1: "",
  image2: "",
  image3: "",
  image4: "",
  image5: "",
  title: "Selectie Feteasca Alba",
  shortDescription: `White`,
  link: "",
  btnText1: "Details",
  btnText2: "",
  dataAosDelay: "0",
  specs: {
    color: "White",
    year: "2023",
    grapeVariety: "",
    wineType: "Dry",
    bottleVolume: "75 cl",
    alcoholContent: "11.5%",
    qualityClassification: "DOC Dealu Mare Pietroasa",
    priceWithoutVAT: "EUR 14",
  },
  fullDescription: ``,
};

const pipe16 = {
  item: "16",
  image: "Gallery/Pietroasa/Selectie-Tamaioasa-Romaneasca.png",
  image1: "",
  image2: "",
  image3: "",
  image4: "",
  image5: "",
  title: "Selectie Tamaioasa Romaneasca",
  shortDescription: `White`,
  link: "",
  btnText1: "Details",
  btnText2: "",
  dataAosDelay: "0",
  specs: {
    color: "White",
    year: "2024",
    grapeVariety: "",
    wineType: "Dry",
    bottleVolume: "75 cl",
    alcoholContent: "13%",
    qualityClassification: "DOC Dealu Mare Pietroasa",
    priceWithoutVAT: "EUR 14",
  },
  fullDescription: ``,
};

const list = [
  mesajEroare,
  pipe1,
  pipe2,
  pipe3,
  pipe4,
  pipe5,
  pipe6,
  pipe7,
  pipe8,
  pipe9,
  pipe10,
  pipe11,
  pipe12,
  pipe13,
  pipe14,
  pipe15,
  pipe16,
];

export default list;
